from enum import Enum


class CategoriaLivro(str, Enum):
    AVENTURA = "AVENTURA"
    BIOGRAFIA = "BIOGRAFIA"
    EDUCACAO = "EDUCACAO"
    FICCAO_CIENTIFICA = "FICCAO_CIENTIFICA"
    HISTORIA = "HISTORIA"
    INFANTIL = "INFANTIL"
    LINGUA_ESTRANGEIRA = "LINGUA_ESTRANGEIRA"
    LITERATURA_BRASILEIRA = "LITERATURA_BRASILEIRA"
    MANUAL = "MANUAL"
    OUTROS = "OUTROS"
    RELIGIAO = "RELIGIAO"
    ROMANCE = "ROMANCE"
    TECNICO = "TECNICO"
    TERROR = "TERROR"
